# CFG Production Table for Lovers Language
# Single source of truth: all productions in one map.
# Used by parsetv2.py for reference; LL(1) parsing table is built from this grammar.
#
from typing import Dict, List, Tuple

PRODUCTION_LIST: List[Tuple[str, List[str]]] = [
    (
        "<program>",
        ["<top_decls_opt>", "love", "(", ")", "{", "<body_func>", "}", "<optional_top_func_semi>"],
    ),
    ("<top_decls_opt>", ["<top_decl>", "<top_decls_opt>"]),
    ("<top_decls_opt>", ["λ"]),
    # Optional `;` after top-level `love()` / `avoidant` / typed function bodies (C++-style `};`).
    ("<optional_top_func_semi>", [";"]),
    ("<optional_top_func_semi>", ["λ"]),
    # Block bodies: declarations and statements may be interleaved (C++-like order).
    ("<body_func>", ["<body_items>"]),
    ("<typed_func_body>", ["<body_items>"]),
    ("<body_items>", ["<local_decl>", "<body_items>"]),
    ("<body_items>", ["id", "<id_or_struct_continuation>", "<body_items>"]),
    ("<body_items>", ["<input_state>", "<body_items>"]),
    ("<body_items>", ["<output_state>", "<body_items>"]),
    ("<body_items>", ["<conditional_state>", "<body_items>"]),
    ("<body_items>", ["<loop_state>", "<body_items>"]),
    ("<body_items>", ["<comeback_state>", "<body_items>"]),
    ("<body_items>", ["<choose_state>", "<body_items>"]),
    ("<body_items>", ["<unary_state>", "<body_items>"]),
    ("<body_items>", ["<break_state>", "<body_items>"]),
    ("<body_items>", ["<continue_state>", "<body_items>"]),
    ("<body_items>", ["λ"]),

    ("<top_decl>", ["dear", "id", "<dear_after_id>"]),
    ("<top_decl>", ["dearest", "id", "<dearest_after_id>"]),
    ("<top_decl>", ["rant", "id", "<rant_after_id>"]),
    ("<top_decl>", ["status", "<status_top_decl>"]),
    ("<top_decl>", ["struct", "id", "{", "<struct_body_opt>", "}", ";"]),
    ("<status_top_decl>", ["id", "<status_after_id>"]),
    ("<top_decl>", ["boundaries", "id", "{", "<boundaries_decls_opt>", "}"]),
    ("<boundaries_decls_opt>", ["<top_decl>", "<boundaries_decls_opt>"]),
    ("<boundaries_decls_opt>", ["λ"]),
    (
        "<top_decl>",
        ["avoidant", "id", "(", "<parameter>", ")", "{", "<body_func>", "}", "<optional_top_func_semi>"],
    ),
    ("<top_decl>", ["const", "<const_decl>"]),

    ("<local_decl>", ["dear", "id", "<dear_tail>"]),
    ("<local_decl>", ["dearest", "id", "<dearest_tail>"]),
    ("<local_decl>", ["rant", "id", "<rant_tail>"]),
    ("<local_decl>", ["status", "<status_local_decl>"]),
    ("<local_decl>", ["const", "<const_decl>"]),
    ("<id_or_struct_continuation>", ["id", "<struct_init_opt>", ";"]),
    ("<id_or_struct_continuation>", ["<id_suffix>"]),
    ("<status_local_decl>", ["id", "<status_tail>"]),
    ("<struct_init_opt>", ["=", "{", "<struct_init_values_opt>", "}"]),
    ("<struct_init_opt>", ["λ"]),
    ("<struct_init_values_opt>", ["<struct_init_item>", "<struct_init_more>"]),
    ("<struct_init_values_opt>", ["λ"]),
    ("<struct_init_more>", [",", "<struct_init_item>", "<struct_init_more>"]),
    ("<struct_init_more>", ["λ"]),
    ("<struct_init_item>", ["<expr>"]),
    ("<struct_init_item>", ["{", "<struct_init_values_opt>", "}"]),

    (
        "<dear_after_id>",
        ["(", "<parameter>", ")", "{", "<typed_func_body>", "}", "<optional_top_func_semi>"],
    ),
    ("<dear_after_id>", ["<dear_tail>"]),
    ("<dear_tail>", ["=", "<dear_expr>", "<dear_multi>", ";"]),
    ("<dear_tail>", ["<dear_multi>", ";"]),
    ("<dear_tail>", ["[", "<dear_array_after_lbracket>"]),
    ("<dear_multi>", [",", "id", "<dear_init_opt>", "<dear_multi>"]),
    ("<dear_multi>", ["λ"]),
    ("<dear_init_opt>", ["=", "<dear_expr>"]),
    ("<dear_init_opt>", ["λ"]),
    ("<dear_expr>", ["id", "<dear_expr_id_tail>"]),
    ("<dear_expr>", ["<dear_term_not_id>", "<dear_next>"]),
    ("<dear_expr_id_tail>", ["<assign_ops>", "<dear_expr>"]),
    ("<dear_expr_id_tail>", ["<factor_tail>", "<dear_tail_after_factor>"]),
    ("<dear_tail_after_factor>", ["<dear_term_next>", "<dear_next>"]),
    ("<dear_next>", ["+", "<dear_term>", "<dear_next>"]),
    ("<dear_next>", ["-", "<dear_term>", "<dear_next>"]),
    ("<dear_next>", ["<dear_term>", "<dear_next>"]),
    ("<dear_next>", ["<<", "<dear_term>", "<dear_next>"]),
    ("<dear_next>", [">>", "<dear_term>", "<dear_next>"]),
    ("<dear_next>", ["λ"]),
    ("<dear_term>", ["<dear_factor>", "<dear_term_next>"]),
    ("<dear_term_next>", ["<dear_factor>", "<dear_term_next>"]),
    ("<dear_term_next>", ["/", "<dear_factor>", "<dear_term_next>"]),
    ("<dear_term_next>", ["%", "<dear_factor>", "<dear_term_next>"]),
    ("<dear_term_next>", ["*", "<dear_factor>", "<dear_term_next>"]),
    ("<dear_term_next>", ["λ"]),
    ("<dear_term_not_id>", ["<dear_factor_not_id>", "<dear_term_next>"]),
    ("<dear_factor>", ["(", "<dear_expr>", ")"]),
    ("<dear_factor>", ["dear_lit"]),
    ("<dear_factor>", ["dearest_lit"]),
    ("<dear_factor>", ["id", "<factor_tail>"]),
    ("<dear_factor>", ["+", "<dear_factor>"]),
    ("<dear_factor>", ["-", "<dear_factor>"]),
    ("<dear_factor>", ["greenflag"]),
    ("<dear_factor>", ["redflag"]),
    ("<dear_factor>", ["++", "id"]),
    ("<dear_factor>", ["--", "id"]),
    ("<dear_expr_not_id>", ["<dear_term_not_id>", "<dear_next>"]),
    ("<dear_factor_not_id>", ["(", "<dear_expr>", ")"]),
    ("<dear_factor_not_id>", ["dear_lit"]),
    ("<dear_factor_not_id>", ["dearest_lit"]),
    ("<dear_factor_not_id>", ["greenflag"]),
    ("<dear_factor_not_id>", ["redflag"]),
    ("<dear_factor_not_id>", ["+", "<dear_factor_not_id>"]),
    ("<dear_factor_not_id>", ["-", "<dear_factor_not_id>"]),
    ("<dear_factor_not_id>", ["++", "id"]),
    ("<dear_factor_not_id>", ["--", "id"]),

    (
        "<dearest_after_id>",
        ["(", "<parameter>", ")", "{", "<typed_func_body>", "}", "<optional_top_func_semi>"],
    ),
    ("<dearest_after_id>", ["<dearest_tail>"]),
    ("<dearest_tail>", ["=", "<dearest_expr>", "<dearest_multi>", ";"]),
    ("<dearest_tail>", ["<dearest_multi>", ";"]),
    ("<dearest_tail>", ["[", "<dearest_array_after_lbracket>"]),
    ("<dearest_multi>", [",", "id", "<dearest_init_opt>", "<dearest_multi>"]),
    ("<dearest_multi>", ["λ"]),
    ("<dearest_init_opt>", ["=", "<dearest_expr>"]),
    ("<dearest_init_opt>", ["λ"]),
    ("<dearest_expr>", ["id", "<dearest_expr_id_tail>"]),
    ("<dearest_expr>", ["<dearest_term_not_id>", "<dearest_next>"]),
    ("<dearest_expr_id_tail>", ["<assign_ops>", "<dearest_expr>"]),
    ("<dearest_expr_id_tail>", ["<factor_tail>", "<dearest_tail_after_factor>"]),
    ("<dearest_tail_after_factor>", ["<dearest_term_next>", "<dearest_next>"]),
    ("<dearest_next>", ["+", "<dearest_term>", "<dearest_next>"]),
    ("<dearest_next>", ["-", "<dearest_term>", "<dearest_next>"]),
    ("<dearest_next>", ["λ"]),
    ("<dearest_term>", ["<dearest_factor>", "<dearest_term_next>"]),
    ("<dearest_term_next>", ["<dearest_factor>", "<dearest_term_next>"]),
    ("<dearest_term_next>", ["/", "<dearest_factor>", "<dearest_term_next>"]),
    ("<dearest_term_next>", ["*", "<dearest_factor>", "<dearest_term_next>"]),
    ("<dearest_term_next>", ["λ"]),
    ("<dearest_term_not_id>", ["<dearest_factor_not_id>", "<dearest_term_next>"]),
    ("<dearest_factor>", ["(", "<dearest_expr>", ")"]),
    ("<dearest_factor>", ["dearest_lit"]),
    ("<dearest_factor>", ["id", "<factor_tail>"]),
    ("<dearest_factor>", ["-", "<dearest_factor>"]),
    ("<dearest_factor>", ["dear_lit"]),
    ("<dearest_factor>", ["greenflag"]),
    ("<dearest_factor>", ["redflag"]),
    ("<dearest_factor>", ["++", "id"]),
    ("<dearest_factor>", ["--", "id"]),
    ("<dearest_factor_not_id>", ["(", "<dearest_expr>", ")"]),
    ("<dearest_factor_not_id>", ["dearest_lit"]),
    ("<dearest_factor_not_id>", ["dear_lit"]),
    ("<dearest_factor_not_id>", ["greenflag"]),
    ("<dearest_factor_not_id>", ["redflag"]),
    ("<dearest_factor_not_id>", ["+", "<dearest_factor_not_id>"]),
    ("<dearest_factor_not_id>", ["-", "<dearest_factor_not_id>"]),
    ("<dearest_factor_not_id>", ["++", "id"]),
    ("<dearest_factor_not_id>", ["--", "id"]),

    (
        "<rant_after_id>",
        ["(", "<parameter>", ")", "{", "<typed_func_body>", "}", "<optional_top_func_semi>"],
    ),
    ("<rant_after_id>", ["<rant_tail>"]),
    ("<rant_tail>", ["=", "<rant_expr>", "<rant_multi>", ";"]),
    ("<rant_tail>", ["<rant_multi>", ";"]),
    ("<rant_tail>", ["[", "<rant_array_after_lbracket>"]),
    ("<rant_multi>", [",", "id", "<rant_init_opt>", "<rant_multi>"]),
    ("<rant_multi>", ["λ"]),
    ("<rant_init_opt>", ["<rant_expr>"]),
    ("<rant_init_opt>", ["λ"]),
    ("<rant_expr>", ["<rant_term>", "<rant_next>"]),
    ("<rant_next>", ["=", "<rant_expr>", "<rant_multi>", ";"]),
    ("<rant_next>", ["+", "<rant_term>", "<rant_next>"]),
    ("<rant_next>", ["λ"]),
    ("<rant_term>", ["<rant_factor>"]),
    ("<rant_factor>", ["(", "<rant_expr>", ")"]),
    ("<rant_factor>", ["rant_lit"]),
    ("<rant_factor>", ["id", "<factor_tail>"]),

    (
        "<status_after_id>",
        ["(", "<parameter>", ")", "{", "<typed_func_body>", "}", "<optional_top_func_semi>"],
    ),
    ("<status_after_id>", ["<status_tail>"]),
    ("<status_tail>", ["=", "<status_expr>", "<status_multi>", ";"]),
    ("<status_tail>", ["<status_multi>", ";"]),
    ("<status_tail>", ["[", "<status_array_after_lbracket>"]),
    ("<status_multi>", ["id", "<status_init_opt>", "<status_multi>"]),
    ("<status_multi>", ["λ"]),
    ("<status_init_opt>", ["=", "<status_expr>"]),
    ("<status_init_opt>", ["λ"]),
    ("<status_lit>", ["greenflag"]),
    ("<status_lit>", ["redflag"]),
    ("<status_expr>", ["<status_and>", "<status_or_next>"]),
    ("<status_or_next>", ["||", "<status_and>", "<status_or_next>"]),
    ("<status_or_next>", ["λ"]),
    ("<status_and>", ["<status_factor>", "<status_and_next>"]),
    ("<status_and_next>", ["&&", "<status_factor>", "<status_and_next>"]),
    ("<status_and_next>", ["λ"]),
    ("<status_factor>", ["not", "<status_factor>"]),
    ("<status_factor>", ["<status_lit>"]),
    ("<status_factor>", ["id", "<status_factor_after_id>"]),
    ("<status_factor>", ["<status_int_compare>"]),
    ("<status_factor>", ["dear_lit"]),
    ("<status_factor>", ["!", "<status_factor>"]),
    ("<status_factor>", ["(", "<status_expr>", ")"]),
    ("<status_factor_after_id>", ["λ"]),
    ("<status_factor_after_id>", ["<rel_op>", "<dear_expr>"]),
    ("<status_int_compare>", ["<dear_expr_not_id>", "<status_int_compare_next>"]),
    ("<status_int_compare_next>", ["<rel_op>", "<dear_expr>"]),
    ("<status_int_compare_next>", ["λ"]),

    ("<statements>", ["id", "<id_or_struct_continuation>", "<statements>"]),
    ("<statements>", ["<input_state>", "<statements>"]),
    ("<statements>", ["<output_state>", "<statements>"]),
    ("<statements>", ["<conditional_state>", "<statements>"]),
    ("<statements>", ["<loop_state>", "<statements>"]),
    ("<statements>", ["<comeback_state>", "<statements>"]),
    ("<statements>", ["<choose_state>", "<statements>"]),
    ("<statements>", ["<unary_state>", "<statements>"]),
    ("<statements>", ["<break_state>", "<statements>"]),
    ("<statements>", ["<continue_state>", "<statements>"]),
    ("<statements>", ["λ"]),

    ("<id_suffix>", ["[", "<array_index_expr>", "]", "<id_suffix>"]),
    ("<id_suffix>", ["<assign_ops>", "<assign_values>", ";"]),
    ("<id_suffix>", ["(", "<arguments>", ")", ";"]),
    ("<id_suffix>", ["<unary_ops>", ";"]),
    ("<id_suffix>", [".", "id", "<id_suffix>"]),
    ("<id_suffix>", ["::", "id", "<id_suffix>"]),
    ("<unary_state>", ["<unary_ops>", "id", ";"]),
    ("<unary_ops>", ["++"]),
    ("<unary_ops>", ["--"]),

    ("<assign_ops>", ["="]),
    ("<assign_ops>", ["+="]),
    ("<assign_ops>", ["-="]),
    ("<assign_ops>", ["*="]),
    ("<assign_ops>", ["/="]),
    ("<assign_ops>", ["%="]),
    ("<assign_values>", ["<expr>"]),

    ("<conditional_state>", ["forever", "(", "<expr>", ")", "{", "<body_func>", "}", "<forevermore_lst>", "<more_opt>"]),
    ("<forevermore_lst>", ["forevermore", "(", "<expr>", ")", "{", "<body_func>", "}", "<forevermore_lst>"]),
    ("<forevermore_lst>", ["λ"]),
    ("<more_opt>", ["more", "{", "<body_func>", "}"]),
    ("<more_opt>", ["λ"]),

    ("<loop_state>", ["<pursue_stmt>"]),
    ("<loop_state>", ["<while_stmt>"]),
    ("<loop_state>", ["<for_stmt>"]),
    ("<pursue_stmt>", ["pursue", "(", "<expr>", ")", "{", "<body_func>", "}"]),
    ("<while_stmt>", ["while", "(", "<expr>", ")", "{", "<body_func>", "}"]),
    ("<for_stmt>", ["for", "(", "<for_init>", ";", "<expr>", ";", "<for_ud>", ")", "{", "<body_func>", "}"]),
    ("<for_init>", ["<data_type>", "id", "=", "<expr_ar>"]),
    ("<for_init>", ["id", "=", "<expr_ar>"]),
    ("<for_ud>", ["id", "<for_ud_tail>"]),
    ("<for_ud_tail>", ["<assign_ops>", "<expr>"]),
    ("<for_ud_tail>", ["<unary_ops>"]),
    ("<for_ud>", ["<unary_ops>", "id"]),

    ("<choose_state>", ["choose", "(", "<expr>", ")", "{", "<phase_lst>", "<bareminimum_opt>", "}"]),

    ("<phase_lst>", ["phase", "<choose_const>", ":", "<body_func>", "<phase_lst_next>"]),
    ("<phase_lst_next>", ["<phase_lst>"]),
    ("<phase_lst_next>", ["λ"]),
    ("<choose_const>", ["dear_lit"]),
 
    ("<bareminimum_opt>", ["bareminimum", ":", "<body_func>"]),
    ("<bareminimum_opt>", ["λ"]),

    ("<comeback_state>", ["comeback", "<expr_opt>", ";"]),
    ("<break_state>", ["breakup", ";"]),
    ("<continue_state>", ["moveon", ";"]),
    ("<expr>", ["<log_expr>"]),
    ("<expr_opt>", ["<expr>"]),
    ("<expr_opt>", ["λ"]),
    ("<log_expr>", ["<and_expr>", "<log_next>"]),
    ("<log_next>", ["||", "<and_expr>", "<log_next>"]),
    ("<log_next>", ["λ"]),
    ("<and_expr>", ["<rel_expr>", "<and_next>"]),
    ("<and_next>", ["&&", "<rel_expr>", "<and_next>"]),
    ("<and_next>", ["λ"]),
    ("<rel_expr>", ["<expr_ar>", "<rel_next>"]),
    ("<rel_next>", ["<rel_op>", "<expr_ar>", "<rel_next>"]),
    ("<rel_next>", ["λ"]),
    ("<rel_op>", ["=="]),
    ("<rel_op>", [".=="]),
    ("<rel_op>", ["!="]),
    ("<rel_op>", ["<"]),
    ("<rel_op>", ["<="]),
    ("<rel_op>", [">"]),
    ("<rel_op>", [">="]),

    ("<expr_ar>", ["<term>", "<expr_next>"]),
    ("<expr_next>", ["+", "<term>", "<expr_next>"]),
    ("<expr_next>", ["-", "<term>", "<expr_next>"]),
    ("<expr_next>", ["λ"]),
    ("<expr_next>", ["<term>", "<expr_next>"]),
    ("<expr_next>", ["++", "<term>", "<expr_next>"]),

    ("<term>", ["<factor>", "<term_next>"]),
    ("<term_next>", ["*", "<factor>", "<term_next>"]),
    ("<term_next>", ["/", "<factor>", "<term_next>"]),
    ("<term_next>", ["%", "<factor>", "<term_next>"]),
    ("<term_next>", ["λ"]),

    ("<factor>", ["(", "<expr>", ")"]),
    ("<factor>", ["id", "<factor_tail>"]),
    ("<factor>", ["dear_lit"]),
    ("<factor>", ["dearest_lit"]),
    ("<factor>", ["rant_lit"]),
    ("<factor>", ["<status_lit>"]),
    ("<factor>", ["-", "<factor>"]),
    ("<factor>", ["+", "<factor>"]),
    ("<factor>", ["++", "<factor>"]),
    ("<factor>", ["--", "<factor>"]),

    ("<factor_tail>", ["[", "<array_index_expr>", "]", "<factor_tail>"]),
    ("<factor_tail>", ["(", "<arguments>", ")"]),
    ("<factor_tail>", ["++"]),
    ("<factor_tail>", ["--"]),
    ("<factor_tail>", [".", "id", "<factor_tail>"]),
    ("<factor_tail>", ["::", "id", "<factor_tail>"]),
    ("<factor_tail>", ["λ"]),

    ("<input_state>", ["give", ">>", "id", "<input_tail>", "<more_input_ids>", ";"]),
    ("<input_state>", ["overshare", "(", "id", ")", ";"]),
    ("<input_tail>", ["[", "<array_index_expr>", "]", "<input_tail>"]),
    ("<input_tail>", ["λ"]),
    ("<more_input_ids>", [">>", "id", "<input_tail>", "<more_input_ids>"]),
    ("<more_input_ids>", ["λ"]),

    ("<output_state>", ["express", "<<", "<output_values>", "<more_output_tail>", ";"]),
    ("<more_output_tail>", ["<<", "<output_values>", "<more_output_tail>"]),
    ("<more_output_tail>", ["λ"]),
    ("<output_values>", ["<expr>"]),
    ("<output_values>", ["periodt"]),

    ("<data_type>", ["dear"]),
    ("<data_type>", ["dearest"]),
    ("<data_type>", ["rant"]),
    ("<data_type>", ["status"]),
    ("<parameter>", ["<function_parameter>", "<multi_parameter>"]),
    ("<parameter>", ["λ"]),
    ("<function_parameter>", ["<data_type>", "id", "<param_array_decl>"]),
    ("<multi_parameter>", [",", "<function_parameter>", "<multi_parameter>"]),
    ("<multi_parameter>", ["λ"]),
    ("<param_array_decl>", ["[", "]", "<param_array_decl>"]),
    ("<param_array_decl>", ["λ"]),
    ("<arguments>", ["<expr>", "<more_arguments>"]),
    ("<arguments>", ["λ"]),
    ("<more_arguments>", [",", "<expr>", "<more_arguments>"]),
    ("<more_arguments>", ["λ"]),

    ("<const_decl>", ["dear", "id", "=", "<dear_expr>", "<const_dear_more>", ";"]),
    ("<const_decl>", ["dearest", "id", "=", "<dearest_expr>", "<const_dearest_more>", ";"]),
    ("<const_decl>", ["rant", "id", "=", "<rant_expr>", "<const_rant_more>", ";"]),
    ("<const_decl>", ["status", "id", "=", "<status_lit>", "<const_status_more>", ";"]),
    ("<const_dear_more>", [",", "id", "=", "<dear_expr>", "<const_dear_more>"]),
    ("<const_dear_more>", ["λ"]),
    ("<const_dearest_more>", [",", "id", "=", "<dearest_expr>", "<const_dearest_more>"]),
    ("<const_dearest_more>", ["λ"]),
    ("<const_rant_more>", [",", "id", "=", "<rant_expr>", "<const_rant_more>"]),
    ("<const_rant_more>", ["λ"]),
    ("<const_status_more>", [",", "id", "=", "<status_lit>", "<const_status_more>"]),
    ("<const_status_more>", ["λ"]),

    ("<array_index_expr>", ["<expr>"]),

    ("<dear_array_source>", ["{", "<dear_array_lit_list>", "}"]),
    ("<dear_array_lit_list>", ["<dear_array_elem>", "<more_dear_array_lit>"]),
    ("<dear_array_lit_list>", ["λ"]),
    ("<dear_array_elem>", ["dear_lit"]),
    ("<dear_array_elem>", ["dearest_lit"]),
    ("<dear_array_elem>", ["id"]),
    ("<dear_array_elem>", ["dear_lit"]),
    ("<dear_array_elem>", ["{", "<dear_array_lit_list>", "}"]),
    ("<dear_array_elem>", ["greenflag"]),
    ("<dear_array_elem>", ["redflag"]),
    ("<more_dear_array_lit>", [",", "<dear_array_elem>", "<more_dear_array_lit>"]),
    ("<more_dear_array_lit>", ["λ"]),
    ("<dear_array_assign>", ["=", "<dear_array_source>"]),
    ("<dear_array_assign>", ["λ"]),
    ("<dear_array_after_lbracket>", ["]", "<dear_array_empty_dims_tail>"]),
    ("<dear_array_after_lbracket>", ["<dear_expr>", "]", "<dear_array_dim_tail>"]),
    ("<dear_array_dim_tail>", ["[", "<dear_expr>", "]", "<dear_array_dim_tail>"]),
    ("<dear_array_dim_tail>", ["<dear_array_assign>", "<dear_multi>", ";"]),
    ("<dear_array_empty_dims_tail>", ["[", "]", "<dear_array_empty_dims_tail>"]),
    ("<dear_array_empty_dims_tail>", ["=", "<dear_array_source>", ";"]),

    ("<dearest_array_source>", ["{", "<dearest_array_lit_list>", "}"]),
    ("<dearest_array_lit_list>", ["<dearest_array_elem>", "<more_dearest_array_lit>"]),
    ("<dearest_array_lit_list>", ["λ"]),
    ("<dearest_array_elem>", ["dearest_lit"]),
    ("<dearest_array_elem>", ["dear_lit"]),
    ("<dearest_array_elem>", ["id"]),
    ("<dearest_array_elem>", ["<dearest_neg_lit>"]),
    ("<dearest_array_elem>", ["greenflag"]),
    ("<dearest_array_elem>", ["redflag"]),
    ("<dearest_array_elem>", ["{", "<dearest_array_lit_list>", "}"]),
    ("<dearest_neg_lit>", ["-", "dearest_lit"]),
    ("<dearest_neg_lit>", ["-", "dear_lit"]),
    ("<more_dearest_array_lit>", [",", "<dearest_array_elem>", "<more_dearest_array_lit>"]),
    ("<more_dearest_array_lit>", ["λ"]),
    ("<dearest_array_assign>", ["=", "<dearest_array_source>"]),
    ("<dearest_array_assign>", ["λ"]),
    ("<dearest_array_after_lbracket>", ["]", "<dearest_array_empty_dims_tail>"]),
    ("<dearest_array_after_lbracket>", ["<dear_expr>", "]", "<dearest_array_dim_tail>"]),
    ("<dearest_array_dim_tail>", ["[", "<dear_expr>", "]", "<dearest_array_dim_tail>"]),
    ("<dearest_array_dim_tail>", ["<dearest_array_assign>", "<dearest_multi>", ";"]),
    ("<dearest_array_empty_dims_tail>", ["[", "]", "<dearest_array_empty_dims_tail>"]),
    ("<dearest_array_empty_dims_tail>", ["=", "<dearest_array_source>", ";"]),

    ("<rant_array_source>", ["{", "<rant_array_lit_list>", "}"]),
    ("<rant_array_lit_list>", ["<rant_array_elem>", "<more_rant_array_lit>"]),
    ("<rant_array_lit_list>", ["λ"]),
    ("<rant_array_elem>", ["rant_lit"]),
    ("<rant_array_elem>", ["id"]),
    ("<rant_array_elem>", ["{", "<rant_array_lit_list>", "}"]),
    ("<more_rant_array_lit>", [",", "<rant_array_elem>", "<more_rant_array_lit>"]),
    ("<more_rant_array_lit>", ["λ"]),
    ("<rant_array_assign>", ["=", "<rant_array_source>"]),
    ("<rant_array_assign>", ["λ"]),
    ("<rant_array_after_lbracket>", ["]", "<rant_array_empty_dims_tail>"]),
    ("<rant_array_after_lbracket>", ["<dear_expr>", "]", "<rant_array_dim_tail>"]),
    ("<rant_array_dim_tail>", ["[", "<dear_expr>", "]", "<rant_array_dim_tail>"]),
    ("<rant_array_dim_tail>", ["<rant_array_assign>", "<rant_multi>", ";"]),
    ("<rant_array_empty_dims_tail>", ["[", "]", "<rant_array_empty_dims_tail>"]),
    ("<rant_array_empty_dims_tail>", ["=", "<rant_array_source>", ";"]),

    ("<status_array_source>", ["{", "<status_array_lit_list>", "}"]),
    ("<status_array_lit_list>", ["<status_array_elem>", "<more_status_array_lit>"]),
    ("<status_array_lit_list>", ["λ"]),
    ("<status_array_elem>", ["greenflag"]),
    ("<status_array_elem>", ["redflag"]),
    ("<status_array_elem>", ["dear_lit"]),
    ("<status_array_elem>", ["dearest_lit"]),
    ("<status_array_elem>", ["id"]),
    ("<status_array_elem>", ["{", "<status_array_lit_list>", "}"]),
    ("<more_status_array_lit>", [",", "<status_array_elem>", "<more_status_array_lit>"]),
    ("<more_status_array_lit>", ["λ"]),
    ("<status_array_assign>", ["=", "<status_array_source>"]),
    ("<status_array_assign>", ["λ"]),
    ("<status_array_after_lbracket>", ["]", "<status_array_empty_dims_tail>"]),
    ("<status_array_after_lbracket>", ["<dear_expr>", "]", "<status_array_dim_tail>"]),
    ("<status_array_dim_tail>", ["[", "<dear_expr>", "]", "<status_array_dim_tail>"]),
    ("<status_array_dim_tail>", ["<status_array_assign>", "<status_multi>", ";"]),
    ("<status_array_empty_dims_tail>", ["[", "]", "<status_array_empty_dims_tail>"]),
    ("<status_array_empty_dims_tail>", ["=", "<status_array_source>", ";"]),

    ("<struct_body_opt>", ["<struct_member>", "<struct_body_opt>"]),
    ("<struct_body_opt>", ["λ"]),
    ("<struct_member>", ["<data_type>", "id", "<struct_field_array_opt>", ";"]),
    ("<struct_member>", ["struct", "id", "id", "<struct_field_array_opt>", ";"]),
    # Left-factored: `[` … `]` so LL(1) can choose `dear_lit` vs `]` after `[`.
    ("<struct_field_array_opt>", ["[", "<struct_dim>", "]", "<struct_field_array_opt>"]),
    ("<struct_field_array_opt>", ["λ"]),
    ("<struct_dim>", ["dear_lit"]),
    ("<struct_dim>", ["λ"]),
]


# By nonterminal: lhs -> list of RHS (each RHS is list of symbols). Easy lookup.
CFG_BY_NONTERMINAL: Dict[str, List[List[str]]] = {}
for (lhs, rhs) in PRODUCTION_LIST:
    if lhs not in CFG_BY_NONTERMINAL:
        CFG_BY_NONTERMINAL[lhs] = []
    CFG_BY_NONTERMINAL[lhs].append(rhs)


def get_productions(lhs: str) -> List[List[str]]:
    """Return all RHS alternatives for nonterminal lhs."""
    return CFG_BY_NONTERMINAL.get(lhs, [])


def is_epsilon(rhs: List[str]) -> bool:
    """True if RHS is epsilon (λ or null)."""
    return rhs in (["λ"], ["null"]) or (len(rhs) == 1 and rhs[0] in ("λ", "null"))
